name: firebase_ui
description: FORK of https://github.com/Maliffic/firebase_ui Firebase auth UI, dart package to mimic the firebaseUI(Google,Facebook,Twitter,Email supported)
version: 2.0.0
author: Nicholas Bowler <crucifixx25@gmail.com>
homepage: https://github.com/maxifom/firebase_ui

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_twitter: ">=1.1.3"

  firebase_auth: ">=0.18.1"

  google_sign_in: ">=4.5.4"
  flutter_facebook_login: ">=3.0.0"

  apple_sign_in: ">=0.1.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/fb-logo.png
    - assets/2.0x/fb-logo.png
    - assets/3.0x/fb-logo.png

    - assets/email-logo.png
    - assets/2.0x/email-logo.png
    - assets/3.0x/email-logo.png

    - assets/go-logo.png
    - assets/2.0x/go-logo.png
    - assets/3.0x/go-logo.png

    - assets/twitter-logo.png
    - assets/2.0x/twitter-logo.png
    - assets/3.0x/twitter-logo.png
